name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker (if needed for private registry)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Backend - Build Docker Image
        run: |
          docker build -t sufferingindex-backend ./backend

      - name: Frontend - Build Docker Image
        run: |
          docker build -t sufferingindex-frontend ./frontend

      - name: Start Docker Compose stack
        run: |
          docker compose -f docker-compose.prod.yml up -d
          sleep 10  # Allow services time to start

      - name: Smoke test Backend (Flask)
        run: |
          curl --fail http://localhost:5000/data || (echo "Backend smoke test failed!" && exit 1)

      - name: Smoke test Frontend (Next.js)
        run: |
          curl --fail http://localhost:3000 || (echo "Frontend smoke test failed!" && exit 1)

      - name: Tear down Docker Compose stack
        if: always()  # Always runs even if previous steps fail
        run: |
          docker compose -f docker-compose.prod.yml down
