name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker system prune
        run: docker builder prune --all --force

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Backend - Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sufferingindex-backend:latest

      - name: Frontend - Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sufferingindex-frontend:latest

      - name: Start Docker Compose stack
        run: |
          docker compose -f docker-compose.prod.yml up -d
          sleep 10  # Allow services time to start

      - name: Smoke test Backend (Flask)
        run: |
          curl --fail http://localhost:5000/data || (echo "Backend smoke test failed!" && exit 1)

      - name: Smoke test Frontend (Next.js)
        run: |
          curl --fail http://localhost:3000 || (echo "Frontend smoke test failed!" && exit 1)

      - name: Tear down Docker Compose stack
        if: always()  # Always runs even if previous steps fail
        run: |
          docker compose -f docker-compose.prod.yml down
